name: Test Action
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        version:
          - 16.0.6
          - 17.0.6
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Install LLVM and Clang
        id: install
        uses: ./
        with:
          version: "${{ matrix.version }}"
      - name: Test install *nix
        if: matrix.os != 'windows-latest'
        shell: bash
        run: >
          LLVM_DIR="${{ steps.install.directory }}"
          if [! -d "$LLVM_DIR"]; then
              echo "llvm dir \"$LLVM_DIR\" does not exists"
              exit 1
          fi
          if [! -d "$LLVM_DIR/bin"]; then
              echo "llvm dir \"$LLVM_DIR/bin\" does not exists"
              exit 1
          fi
          if [! -f "$LLVM_DIR/bin/llvm-config"]; then
              echo "llvm dir \"$LLVM_DIR/bin/llvm-config\" does not exists"
              exit 1
          fi
          "$LLVM_DIR/bin/llvm-config" --version && llvm-config --version

      - name: Test install *nix
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: >-
          $llvmDir = "${{ steps.install.directory }}"
          if (!Test-Path $llvmDir -PathType Container) {
            throw "$llvmDir was not found"
          }
          if (!Test-Path "$llvmDir\bin" -PathType Container) {
            throw "$llvmDir\bin was not found"
          }
          if (!Test-Path "$llvmDir\bin\llvm-config.exe" -PathType Leaf) {
            throw "$llvmDir\bin\llvm-config.exe was not found"
          }
          & '$llvmDir\bin\llvm-config.exe' --version
          & llvm-config.exe --version
